# Site settings
title: YoungMin Resume
description: Resume
baseurl: "/resume" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. https://example.com/
updated: 2023

lang : ko-KR

# Landing Page
username: YoungMin CHoi
typing_text: Game Client Developer
email: psymchoi@gmail.com
github_username: Jpot777
linkedin_username: youngmin-choi-bs-2405b6208

# About Me Section
show_aboutme_card: true
about_me_title: Who Am I

# Skills Section
show_skills_card: true
skills_title: Skills

# Timeline Section
show_timeline_card: true
timeline_title: My Journey
cv_download_link: https://www.notion.so/73abb5de2f794087839160c22946f1fc

# Projects Section
show_projects_card: true
show_projects: false
projects_title: Things I Have Built
show_os_projects: true
os_projects_title: Open Source Projects

# CONTACT SECTION
show_contact_card: true
contact_title: Get In Touch

# Github-Metadata
repository: Jpot777
projects:
  # pushed or stars
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

# Google-analytics
google-analytics:
  id: "GTM-PJ2P865S"

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
